// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "HTML & CSS"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Python"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Game Development"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "App Development"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Frontend Development"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Infrastructure.Entities.CoursesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Articles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutherBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutherImageAltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseImageAltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceBookFollowers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<string>("LearnPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LikesInNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LikesInPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reviews")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowcaseImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViewHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Views")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTubeSubscribers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessTime = "Full lifetime access",
                            Articles = "18",
                            AutherBio = "Dolor ipsum amet cursus quisque porta adipiscing. Lorem convallis malesuada sed maecenas. Ac dui at vitae mauris cursus in nullam porta sem. Quis pellentesque elementum ac bibendum. Nunc aliquam in tortor facilisis. Vulputate eget risus, metus phasellus. Pellentesque faucibus amet, eleifend diam quam condimentum convallis ultricies placerat. Duis habitasse placerat amet, odio pellentesque rhoncus, feugiat at. Eget pellentesque tristique felis magna fringilla.",
                            AutherImageAltText = "Albert Flores image",
                            AuthorImage = "albert-flores.svg",
                            AuthorName = "Robert Fox",
                            CategoryId = 1,
                            CourseDescription = "Suspendisse natoque sagittis, consequat turpis. Sed tristique tellus morbi magna. At vel senectus accumsan, arcu mattis id tempor. Tellus sagittis, euismod porttitor sed tortor est id. Feugiat velit velit, tortor ut. Ut libero cursus nibh lorem urna amet tristique leo. Viverra lorem arcu nam nunc at ipsum quam. A proin id sagittis dignissim mauris condimentum ornare. Tempus mauris sed dictum ultrices.",
                            CourseImage = "course_one.svg",
                            CourseImageAltText = "course one",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2641),
                            FaceBookFollowers = "240",
                            IsBestSeller = true,
                            LearnPoints = "[\"Sed lectus donec amet eu turpis interdum.\",\"Nulla at consectetur vitae dignissim porttitor.\",\"Phasellus id vitae dui aliquet mi.\",\"Integer cursus vitae, odio feugiat iaculis aliquet diam, et purus.\",\"In aenean dolor diam tortor orci eu.\"]",
                            LikesInNumbers = "4.2",
                            LikesInPercent = "94",
                            Price = "12.50",
                            ProgramDetailsText = "[\"Nulla faucibus mauris pellentesque blandit faucibus non. Sit ut et at suspendisse gravida hendrerit tempus placerat.\",\"Lobortis diam elit id nibh ultrices sed penatibus donec. Nibh iaculis eu sit cras ultricies. Nam eu eget etiam egestas donec scelerisque ut ac enim. Vitae ac nisl, enim nec accumsan vitae est.\",\"Duis euismod enim, facilisis risus tellus pharetra lectus diam neque. Nec ultrices mi faucibus est. Magna ullamcorper potenti elementum ultricies auctor nec volutpat augue.\",\"Morbi porttitor risus imperdiet a, nisl mattis. Amet, faucibus eget in platea vitae, velit, erat eget velit. At lacus ut proin erat.\",\"Risus morbi euismod in congue scelerisque fusce pellentesque diam consequat. Nisi mauris nibh sed est morbi amet arcu urna. Malesuada feugiat quisque consectetur elementum diam vitae. Dictumst facilisis odio eu quis maecenas risus odio fames bibendum.\",\"Quis risus quisque diam diam. Volutpat neque eget eu faucibus sed urna fermentum risus. Est, mauris morbi nibh massa.\"]",
                            ProgramDetailsTitle = "[\"Introduction. Getting started\",\"The ultimate HTML developer: advanced HTML\",\"CSS \\u0026 CSS3: basic\",\"JavaScript basics for beginners\",\"Understanding APIs\",\"C# and .NET from beginner to advanced\"]",
                            Resources = "25",
                            Reviews = "1.2",
                            ShowcaseImage = "showcase_image_1.svg",
                            Title = "Fullstack Web Developer Course from Scratch",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2642),
                            ViewHours = "220",
                            YouTubeSubscribers = "180"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Jenny Wilson & Marvin McKinney",
                            CategoryId = 2,
                            CourseImage = "course_two.svg",
                            CourseImageAltText = "course two",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2660),
                            IsBestSeller = false,
                            LikesInNumbers = "3.1",
                            LikesInPercent = "92",
                            Price = "15.99",
                            Title = "HTML, CSS, JavaScript Web Developer",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2661),
                            ViewHours = "160"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Albert Flores",
                            CategoryId = 6,
                            CourseImage = "course_three.svg",
                            CourseImageAltText = "course three",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2663),
                            DiscountPrice = "9.99",
                            IsBestSeller = false,
                            LikesInNumbers = "2.7",
                            LikesInPercent = "98",
                            Price = "44.99",
                            Title = "The Complete Front-End Web Development Course",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2663),
                            ViewHours = "100"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Marvin McKinney",
                            CategoryId = 5,
                            CourseImage = "course_four.svg",
                            CourseImageAltText = "course four",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2665),
                            IsBestSeller = false,
                            LikesInNumbers = "3.1",
                            LikesInPercent = "92",
                            Price = "15.99",
                            Title = "iOS & Swift - The Complete iOS App Development Course",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2666),
                            ViewHours = "220"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Esther Howard",
                            CategoryId = 3,
                            CourseImage = "course_five.svg",
                            CourseImageAltText = "course five",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2668),
                            IsBestSeller = true,
                            LikesInNumbers = "4.2",
                            LikesInPercent = "94",
                            Price = "12.50",
                            Title = "Data Science & Machine Learning with Python",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2668),
                            ViewHours = "220"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Robert Fox",
                            CategoryId = 2,
                            CourseImage = "course_six.svg",
                            CourseImageAltText = "course six",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2670),
                            IsBestSeller = false,
                            LikesInNumbers = "4.2",
                            LikesInPercent = "94",
                            Price = "10.50",
                            Title = "Creative CSS Drawing Course: Make Art With CSS",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2670),
                            ViewHours = "220"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Ralph Edwards",
                            CategoryId = 4,
                            CourseImage = "course_seven.svg",
                            CourseImageAltText = "course seven",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2672),
                            IsBestSeller = false,
                            LikesInNumbers = "3.1",
                            LikesInPercent = "92",
                            Price = "18.99",
                            Title = "Blender Character Creator v2.0 for Video Games Design",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2673),
                            ViewHours = "160"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Albert Flores",
                            CategoryId = 4,
                            CourseImage = "course_eight.svg",
                            CourseImageAltText = "course eight",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2675),
                            DiscountPrice = "12.99",
                            IsBestSeller = false,
                            LikesInNumbers = "2.7",
                            LikesInPercent = "98",
                            Price = "44.99",
                            Title = "The Ultimate Guide to 2D Mobile Game Development with Unity",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2675),
                            ViewHours = "100"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Jenny Wilson",
                            CategoryId = 5,
                            CourseImage = "course_nine.svg",
                            CourseImageAltText = "course nine",
                            Created = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2704),
                            IsBestSeller = false,
                            LikesInNumbers = "3.1",
                            LikesInPercent = "92",
                            Price = "14.50",
                            Title = "Learn JMETER from Scratch on Live Apps-Performance Testing",
                            Updated = new DateTime(2024, 4, 3, 13, 43, 9, 237, DateTimeKind.Utc).AddTicks(2705),
                            ViewHours = "160"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.SubscribeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdvertisingUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("DailyNewsLetter")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EventUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("Podcasts")
                        .HasColumnType("bit");

                    b.Property<bool>("StartupsWeekly")
                        .HasColumnType("bit");

                    b.Property<bool>("WeekInReviews")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Subscribe");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Entities.CoursesEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
